[package]
name = "convenience-utils"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0-or-later"

[dependencies]
which = "7.0.0"
xflags = "0.3.2"

[profile.release]
lto = true
strip = true
codegen-units = 1
