name: Build debug binaries (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build release
      run: cargo build --profile dev --verbose
    - name: Run release tests release
      run: cargo test --profile dev --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: |
          target/release/
          !target/release/*.d
          !target/release/*.rlib
          !target/release/deps/
          !target/release/build/
          !target/release/incremental/
      